#!/bin/bash
# dual-write-sync.sh — Dual-write hook: Engram ↔ Disk fallback
#
# Purpose: Write observation to disk (.pipeline/) AFTER Engram mem_save succeeds
# Called by: post-mem-save hook trigger (when mem_save succeeds)
# Arguments: $1=cajon (topic_key), $2=content, $3=project_dir (default: .)
#
# Behavior:
#   - Atomic write using temp file + rename (no corruption on crash)
#   - Creates .pipeline/ directory if missing
#   - On success: logs ✅ message
#   - On failure: logs ⚠️ warning but doesn't block (non-critical)
#
# Safety: Uses 'set -euo pipefail' for strict error handling

set -euo pipefail

# Arguments with defaults
CAJON="${1:-}"
CONTENT="${2:-}"
PROJECT_DIR="${3:-.}"

# Validation
if [ -z "$CAJON" ] || [ -z "$CONTENT" ]; then
    echo "⚠️  dual-write-sync.sh: Missing arguments (CAJON and CONTENT required)" >&2
    exit 1
fi

# Derive disk path from topic_key (replace "/" with "-")
# Example: "atlas/boot-state" → "atlas-boot-state.md"
SAFE_CAJON="${CAJON//\//-}"
DISK_PATH="${PROJECT_DIR}/.pipeline/${SAFE_CAJON}.md"

# Create .pipeline directory if not exists
PIPELINE_DIR="$(dirname "$DISK_PATH")"
mkdir -p "$PIPELINE_DIR" 2>/dev/null || {
    echo "⚠️  dual-write-sync.sh: Could not create $PIPELINE_DIR" >&2
    exit 1
}

# Atomic write pattern: temp file + rename
# This ensures file is either complete or missing (no corruption)
TEMP_FILE="${DISK_PATH}.tmp.$$"

# Write to temp file
cat > "$TEMP_FILE" << EOF
# $CAJON
# Generated by dual-write-sync.sh (Phase 0.6A+)
# Timestamp: $(date -u +%Y-%m-%dT%H:%M:%SZ)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

$CONTENT
EOF

# Atomic rename (atomic on POSIX systems)
mv "$TEMP_FILE" "$DISK_PATH" 2>/dev/null || {
    echo "⚠️  dual-write-sync.sh: Could not write to $DISK_PATH" >&2
    # Don't exit 1 — dual-write is fallback, not critical
    exit 0
}

# Success
echo "✅ Dual-write: $CAJON → $DISK_PATH"
exit 0
