#!/bin/bash
# install-pre-push-hook.sh — Install GitHub Policy pre-push hook
# Usage: bash .claude/scripts/install-pre-push-hook.sh

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
HOOK_DIR="$REPO_ROOT/.git/hooks"
HOOK_FILE="$HOOK_DIR/pre-push"
POLICY_SCRIPT="$REPO_ROOT/.claude/scripts/pre-push-check.sh"

echo "🔒 Installing GitHub Policy pre-push hook..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Repository: $REPO_ROOT"
echo ""

# Verify repository is initialized
if [ ! -d "$REPO_ROOT/.git" ]; then
    echo "❌ ERROR: Not a git repository. Run 'git init' first."
    exit 1
fi

# Verify pre-push-check.sh exists
if [ ! -f "$POLICY_SCRIPT" ]; then
    echo "❌ ERROR: Pre-push check script not found at:"
    echo "   $POLICY_SCRIPT"
    exit 1
fi

# Check if hook already exists
if [ -f "$HOOK_FILE" ]; then
    echo "⚠️  Pre-push hook already exists. Checking if it's current..."

    # Backup existing hook
    BACKUP_FILE="$HOOK_FILE.backup.$(date +%Y%m%d-%H%M%S)"
    cp "$HOOK_FILE" "$BACKUP_FILE"
    echo "   Backed up existing hook to: $BACKUP_FILE"
fi

# Create the pre-push hook file
echo "Creating pre-push hook..."
cat > "$HOOK_FILE" << 'HOOK'
#!/bin/bash
# GitHub Policy pre-push hook
# Auto-generated by install-pre-push-hook.sh
# This hook enforces security checks before pushing to GitHub

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
POLICY_SCRIPT="$REPO_ROOT/.claude/scripts/pre-push-check.sh"

# Verify policy script exists
if [ ! -f "$POLICY_SCRIPT" ]; then
    echo "❌ ERROR: Pre-push policy script not found at $POLICY_SCRIPT"
    echo "Cannot verify push safety. Aborting push."
    exit 1
fi

# Run the pre-push checks
# Pass remote and branch as arguments (automatically provided by git hook)
bash "$POLICY_SCRIPT" "$@"
exit $?
HOOK

# Make hook executable
chmod +x "$HOOK_FILE"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Pre-push hook installed successfully"
echo ""
echo "Details:"
echo "  Hook location: $HOOK_FILE"
echo "  Policy script: $POLICY_SCRIPT"
echo "  Permissions: $(ls -l $HOOK_FILE | awk '{print $1}')"
echo ""
echo "Next steps:"
echo "  1. Test with a clean commit:"
echo "     git commit --allow-empty -m 'test: verify hook'"
echo "  2. Try to push:"
echo "     git push origin HEAD"
echo "  3. Hook should display check results"
echo ""
echo "To disable the hook temporarily:"
echo "  git push origin <branch> --no-verify"
echo ""
echo "To remove the hook permanently:"
echo "  rm $HOOK_FILE"
echo ""
